---
- name: wait for vm status to be stopped
  kubernetes.core.k8s_info:
    api_version: "{{ kubevirt_boot_winpe_api_version_virtual_machine }}"
    kind: VirtualMachine
    name: "{{ hostvars[vm].labels['vm.kubevirt.io/name'] }}"
    namespace: "{{ kubevirt_boot_winpe_target_namespace }}"
    verify_ssl: false
    api_key: "{{ api_key }}"
  register: vm_info
  until:
    - (vm_info.resources | default([])) | length > 0
    - vm_info.resources[0].status.printableStatus is defined
    - vm_info.resources[0].status.printableStatus == 'Stopped'
  delay: 5
  retries: 30
  failed_when: false
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: vm
  when:
    - nodes is defined
    - hostvars[vm].uid is defined
    - hostvars[vm].labels['vm.kubevirt.io/name'] is defined
    - (nodes | json_query(query)) | length > 0
  vars:
    query: "@[?name==`{{ hostvars[vm].labels['vm.kubevirt.io/name'] }}`]"
