---
- name: download winpe addon
  block:
    - name: set win_adk_winpe_addon_iso_path
      ansible.builtin.set_fact:
        win_adk_winpe_addon_iso_path: "{{ create_winpe_temp_directory }}\\adkwinpe.iso"

    - name: download winpe addon iso file
      ansible.windows.win_get_url:
        dest: "{{ win_adk_winpe_addon_iso_path }}"
        url: "{{ win_adk_winpe_addon_iso_download_url }}"
      register: download_adk_winpe_addon_iso
      until: download_adk_winpe_addon_iso is success
      delay: 3
      retries: 5
  when:
    - (":" in win_adk_winpe_addon_iso_path)
    - (not adk_winpe_addon_iso_file.stat.exists)

- name: install windows winpe addon
  block:
    - name: mount winpe addon iso
      community.windows.win_disk_image:
        image_path: "{{ win_adk_winpe_addon_iso_path }}"
        state: present
      register: adk_winpe_addon_disk_image_out

    - name: install windows winpe addon
      ansible.windows.win_package:
        path: "{{ adk_winpe_addon_disk_image_out.mount_paths[0] }}adkwinpesetup.exe"
        product_id: "{{ create_winpe_win_adk_winpe_addon_product_id }}"
        arguments: /quiet /installpath c:\ADK /norestart /ceip off /features {{ create_winpe_win_adk_winpe_addon_features }}
  always:
    - name: unmount winpe iso
      community.windows.win_disk_image:
        image_path: "{{ win_adk_winpe_addon_iso_path }}"
        state: absent
