apiVersion: {{ kubevirt_upload_dv_api_version }}
kind: DataVolume
metadata:
  name: iso-{{ iso_file_check.stat.path | win_basename | to_uuid }}
  generation: 5
  namespace: {{ kubevirt_upload_target_namespace }}
  labels:
    iso.file.name: {{ iso_file_label }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  pvc:
    accessModes:
      - {{ kubevirt_upload_pvc_access_mode }}
    dataSource: null
    resources:
      requests:
        storage: {{ (((iso_file_check.stat.size/1024/1024)|round(0, 'ceil')|int) + 1024)|string }}Mi
    storageClassName: {{ kubevirt_upload_pvc_storage_class }}
    volumeMode: {{ kubevirt_upload_pvc_volume_mode }}
  source:
    upload: {}